### ISSUE TITLE
Suggestions on your ReadME file.

### ISSUE THREAD

**Issue by gjeometriku** [kosa12/Hyprland_dotfiles#1]
Hello kosa, 
Your rice is splendid and I love it a lot. I'm new on Arch and Hyprland and have only tried rices with instructions this last week. Would it be possible that you, somehow, provide some instructions or whatsoever to download and install your rice? Including pkgs etc? It would be of great help.
Thanks,
Primedust

**Comment by kosa12** [comment]
Hello,
Yes, I can expand the README file, but there is nothing valuable that I think I can add more. I linked SolDoesTech's rice, that's where I started and modified his rice. Every program is installed through AUR and I just modified thier config file in ~/.config folder

Hope this helps a little, if not, I can provide more detail, but in the near future, in the current time, I don't have much time to edit this

**Comment by gjeometriku** [comment]
What about font? What font have you downloaded? Or you didnt download any? Cuz i Checked your icons, and based on my past experience, icons always fail to show up for me.
And also your terminal, I dont see any zsh conf or something.
Please help me when you get free time :D

**Comment by kosa12** [comment]
My font is Cantarell Bold, but the icons wont show up in the editor for me neither, so i was just hoping and praying that i copied the good one. I don't use zsh, i have bash with kitty, and i used 'oh my bash' for riceing.

**Comment by gjeometriku** [comment]
Hey mate thanks. You have been really helpful till now.
If I may ask, do you know why I have this weird distortion in my wallpaper : 
![image](https://github.com/kosa12/Hyprland_dotfiles/assets/76454167/823648c3-1b74-4513-9b6e-f84f1eed0015)
I've set my monitor and its resolution on all hyprland.conf files but this still persists.

**Comment by kosa12** [comment]
with what did you set the wallpaper, what program?

**Comment by gjeometriku** [comment]
not any app , i just moved it to the "backgrounds" folder
with other backgrounds

**Comment by kosa12** [comment]
Yes, but probably you have a config file that gets the background from the folder, maybe look if the program, (swww/feh/nitrogen maybe) uses strech or fit or idk something modifier

**Comment by gjeometriku** [comment]
Oh my bad, Im already using sww. How can I fix this now?

**Comment by kosa12** [comment]
hmmm i dont think the problem will be with swww, other wallpapers work correctly? other programs are also stretched? Make sure to check out the hyprland config file so that the resolution is the displays resolution and the scaling is 1

**Comment by gjeometriku** [comment]
No only wallpaper is weirdly out of place. 
Yes ive set everything to 1 and correct resolution.

**Comment by kosa12** [comment]
My best bet is that you tried to switch themes on the navbar (the v4 on the top left) and the animation stuck, try to delete that from the navbar config, reboot and hopefully it will work

**Comment by gjeometriku** [comment]
Actually I did try to switch between themes.
Which file is that so I can delete and reboot

**Comment by kosa12** [comment]
I updated the hyprv_util file, let's see if it works. Now only one theme is available. Make sure that the waybar config files stay the same, or change it every occurring place

**Comment by gjeometriku** [comment]
Sadly it didn't work out. Could it be any other way I can set wallpaper? Through hyprpaper or something?

**Comment by kosa12** [comment]
I used for some time a program called `feh`, it's small and not a bunch of bloat, you can try that. It's also simple to operate. Or use nitrogen if you have multiple monitors and want to set different wallpapers for them

**Comment by kosa12** [comment]
I will close this issue, cuz I don't think I can provide more help than any manual or other source on the internet right now, right here. This issue I don't think belongs here.
